title: EniDev
description: Guías sobre temas de bases de datos y programación
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jemoji